version: '3'

services:
  apache:
    container_name: ${COMPOSE_PROJECT_NAME}_apache
    build:
      context: ./apache
      dockerfile: Dockerfile
      args:
        - APACHE_DIR=${APACHE_DIR}
        - WEB_USER=${WEB_USER}
        - WEB_GROUP=${WEB_GROUP}
    image: millennium/apache
    ports:
      - ${APACHE_HOST_PORT}:80
    environment:
      - APACHE_DIR=${APACHE_DIR}
      - WEB_USER=${WEB_USER}
      - WEB_GROUP=${WEB_GROUP}
      - APP_ROOT_DIR=${APP_ROOT_DIR}
    volumes:
      - ./src:${APP_DIR}
      - ./apache/httpd.conf:${APACHE_DIR}/conf/httpd.conf
      - ./logs/apache:${APACHE_LOG_DIR}
    depends_on:
      - php

  php:
    container_name: ${COMPOSE_PROJECT_NAME}_php
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        - PHP_DIR=${PHP_DIR}
        - WEB_USER=${WEB_USER}
        - WEB_GROUP=${WEB_GROUP}
    image: millennium/php
    volumes:
      - ./src:${APP_DIR}
      - ./logs/php:${PHP_LOG_DIR}
    environment:
      - PHP_DIR=${PHP_DIR}
      - WEB_USER=${WEB_USER}
      - WEB_GROUP=${WEB_GROUP}
    depends_on:
      - mysql

  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
      args:
        - MYSQL_CONTAINER_USER=${MYSQL_CONTAINER_USER}
        - MYSQL_CONTAINER_GROUP=${MYSQL_CONTAINER_GROUP}
    image: millennium/mysql
    ports:
      - ${MYSQL_HOST_PORT}:3306
    command: mysqld --sql_mode=""
    volumes:
      - ./logs/mysql:${MYSQL_LOG_DIR}
      - ./mysql/database:${MYSQL_DATA_DIR}
    environment:
      - MYSQL_CONTAINER_USER=${MYSQL_CONTAINER_USER}
      - MYSQL_CONTAINER_GROUP=${MYSQL_CONTAINER_GROUP}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${COMPOSE_PROJECT_NAME}

  yarn:
    container_name: ${COMPOSE_PROJECT_NAME}_yarn
    build:
      context: ./yarn
      dockerfile: Dockerfile
    image: millennium/yarn
